### ISSUE TITLE
Add OpenGraph tags

### ISSUE THREAD

**Issue by ai** [ramoona/banks-db-demo#11]
If we write links to demo page in Facebook, right now we will get:

![rpp4xbn](https://cloud.githubusercontent.com/assets/19343/13408624/e6c4ff6c-df3f-11e5-99bf-590ab2a4c4b9.png)

Link card has no image and no description.

We should cover this case and add OpenGraph meta-tags (they are common for every social network). We need some screenshot example like in `banks-db`’s `README.md` and short description.

Here is useful links:
- [OpenGraph Debugger](https://developers.facebook.com/tools/debug/), because main facebook caches links cards.
- [Facebook Best Practices](https://developers.facebook.com/docs/sharing/best-practices), they are common for VK too.
- [Choosing a best OG image size](http://www.h3xed.com/web-and-internet/how-to-use-og-image-meta-tag-facebook-reddit)

I think Facebook sharing is important for demo page, because non-coder designers is a good client market too :).

**Comment by ramoona** [comment]
done 95b014068d9860a3271ff3b86022a0950928114a
