### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by ai** [ramoona/banks-db-demo#7]
1. HTTPS is better for any page with bankcard number.
2. Chrome enables bankcard number autocomplete on HTTPS pages.

But it is long-term issue, because seems there is no easy way to enable HTTPS on GitHub Pages right now: https://github.com/isaacs/github/issues/156

**Comment by ai** [comment]
@ramoona now HTTPS is possible on GitHub Pages https://github.com/blog/2186-https-for-github-pages

**Comment by ramoona** [comment]
@ai thx for reminding :) done

**Comment by ai** [comment]
It is also a good reason to remind project for users - you could write a tweet that demo page become safer by GH Pages HTTPS and now it is easy to check your card because Google Chrome has bank card autofill (for HTTPS only).

**Comment by ramoona** [comment]
@ai yep, but I need to make some changes in the form first

**Comment by ai** [comment]
Sure. If you need help, some of my friends want some easy task to learn open source. I can send them to this task.

**Comment by ramoona** [comment]
would be good! you can send them to issue #18
